#!/usr/bin/env bash

_armada()
{
    local cur prev opts base
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    opts="name join promote shutdown dockyard list info run stop restart recover ssh build push create version diagnose"


    case "${prev}" in
        list|stop|restart|ssh|diagnose)
            local services=$(armada list | grep -E "([0-9]{1,3}[\.]){3}[0-9]{1,3}" | awk '{print($1)}' | tr '\n' ' ')
            COMPREPLY=( $(compgen -W "${services}" -- ${cur}) )
            return 0
            ;;
        *)
        ;;
    esac

   COMPREPLY=($(compgen -W "${opts}" -- ${cur}))
   return 0
}
complete -F _armada armada