#!/bin/bash

_armada()
{
    local cur prev opts base
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    opts="name join promote shutdown dockyard list info run stop restart recover ssh build push create version diagnose"


    case "${prev}" in
        armada)
            if [ $COMP_CWORD -eq 1 ];then
                COMPREPLY=( $(compgen -W "${opts}" -- ${cur}))
            fi
            return 0
            ;;
        list)
            if [ $COMP_CWORD -eq 2 ];then
                local services=$(armada list | sed '1d' | awk '{print($1)}' | tr '\n' ' ')
                COMPREPLY=( $(compgen -W "${services}" -- ${cur}) )
            fi
            return 0
            ;;
        stop|restart|ssh|diagnose)
            local services=$(armada list | sed '1d' | awk '{print($1)}' | tr '\n' ' ')
            COMPREPLY=( $(compgen -W "${services}" -- ${cur}) )
            return 0
            ;;
        dockyard)
            local dockyard_opts="set list delete default"
            COMPREPLY=( $(compgen -W "${dockyard_opts}" -- ${cur}) )
            return 0
            ;;
        default|delete)
            if [ $COMP_CWORD -eq 3 ] && [ "${COMP_WORDS[1]}" = "dockyard" ];then
                local dockyards=$(armada dockyard list  | sed -e '1d' -e 's/->/ /' | awk '{print($1)}' | tr '\n' ' ')
                COMPREPLY=( $(compgen -W "${dockyards}" -- ${cur}) )
            fi
            return 0
            ;;
        --ship)
            local ships=$(armada info 2>/dev/null | sed -e '1d' -e 's/->/ /' | awk '{print($1)}' | tr '\n' ' ')
            COMPREPLY=( $(compgen -W "${ships}" -- ${cur}) )
            return 0
            ;;
        --dockyard|-d)
            local dockyards=$(armada dockyard list  | sed -e '1d' -e 's/->/ /' | awk '{print($1)}' | tr '\n' ' ')" local"
            COMPREPLY=( $(compgen -W "${dockyards}" -- ${cur}) )
            return 0
            ;;
        --base-template|-b)
            local template_opts="python python3 node"
            COMPREPLY=( $(compgen -W "${template_opts}" -- ${cur}) )
            return 0
            ;;
        recover)
            _filedir
            return 0
            ;;
        *)
        ;;
    esac
    return 0
}

complete -F _armada armada