#!/bin/bash

check_interface() {
    echo "checking $1 $port"
    if [[ "${port}" == */udp ]]; then
        # -v is necessary, otherwise nc always returns 0 for UDP ports.
        nc -z -u -v $1 $(cut -d/ -f1 <<< ${port})
    else
        nc -z $1 ${port}
    fi
}

port=80
if [ -n "$1" ]; then
    port="$1"
fi

ips=`ifconfig -a|grep -w 'inet'|awk '{print $2}'|sed 's/[^0-9\.]//g'`

for ip in ${ips}; do
    check_interface ${ip}

    if [ $? -eq 0 ]; then
        exit 0
    fi
done

exit 2
