FROM docker.io/ubuntu:20.04
MAINTAINER Cerebro <cerebro@ganymede.eu>

ENV LANG='C.UTF-8' LC_ALL='C.UTF-8'
ENV DISTRIB_CODENAME=focal DISTRIB_RELEASE=20.04
ENV CONFIG_DIR config

ENV MICROSERVICE_VERSION 2.11.0

RUN apt-get update && apt-get upgrade -y

# Set up container's timezone
RUN DEBIAN_FRONTEND="noninteractive" TZ="Etc/UTC" apt-get install -y tzdata

#--- Install common utils ---
RUN apt-get install -y --no-install-recommends \
    python3 python3-dev python3-pip supervisor git curl mc less software-properties-common \
    wget vim gcc nano unzip apt-utils net-tools cron netcat sudo file iproute2 bash-completion

#--- Install haproxy ---
RUN add-apt-repository -y ppa:vbernat/haproxy-2.2
RUN apt-get update
RUN apt-get install -y --no-install-recommends haproxy

#--- Install armada ---
COPY ./armada-microservice_${MICROSERVICE_VERSION}_amd64.deb /tmp/armada-microservice_${MICROSERVICE_VERSION}_amd64.deb
RUN dpkg -i /tmp/armada-microservice_${MICROSERVICE_VERSION}_amd64.deb || true
RUN apt-get install -y --fix-broken --no-install-recommends
RUN dpkg -l armada-microservice

#--- Cleanup ---
RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/*

CMD ["microservice", "bootstrap"]
